Migration support for older mupdf-js library
ArtifexSoftware/mupdf.js pull request #105
Opened 2024-07-21 20:33 UTC by andytango

This PR includes documentation for migrating from, and API-compatible functions with https://github.com/andytango/mupdf-js.

FAO @jamie-lemon

2024-07-21 20:34 UTC, andytango commented
I have read the CLA Document and I hereby sign the CLA

2024-07-23 11:52 UTC, jamie-lemon commented
@ccxvii Would you mind reviewing the changes in the mupdf typescript , wasm related and c files here?

2024-08-01 20:58 UTC, jamie-lemon requested changes
I wonder if it is worth getting some of the tasks function case sensitivity finessed and consistent?

For example:
`loadPdf` -> `loadPDF`
`drawPageAsPng` -> `drawPageAsPNG`
`drawPageAsSvg` -> `drawPageAsSVG`
`drawPageAsHtml` -> `drawPageAsHTML`

2024-08-07 16:21 UTC, ccxvii commented
drawPageAsSvg can be implemented using plain JS without needing to add a C function:

```
export function drawPageAsSvg(document: mupdf.PDFDocument, pageNumber: number): string {
        const page = document.loadPage(pageNumber)
        const buf = new mupdf.Buffer()
        const wri = new mupdf.DocumentWriter(buf, "svg", "")
        const dev = wri.beginPage(page.getBounds())
        page.run(dev, mupdf.Matrix.identity)
        dev.close()
        wri.endPage()
        return buf.asString()
}
```

2024-08-07 21:43 UTC, jamie-lemon commented
@andytango If you can fix up the case sensitivity - see: https://github.com/ArtifexSoftware/mupdf.js/pull/105#pullrequestreview-2213952738 and do `drawPageAsSVG` as Tor suggests without the need for the C function - https://github.com/ArtifexSoftware/mupdf.js/pull/105#issuecomment-2273849892 then I think we are all good.

2024-08-18 08:53 UTC, andytango commented
@jamie-lemon  PR updated as requested

2024-08-19 12:25 UTC, jamie-lemon requested changes

2024-08-19 12:25 UTC, jamie-lemon commented on docs/how-to-guide/migration/index.rst
> +We provide a `loadPdf` function that is similar to the `load` method in `mupdf-js`.
`loadPdf` -> `loadPDF`

2024-08-19 12:25 UTC, jamie-lemon commented on docs/how-to-guide/migration/index.rst
> +    import { loadPdf } from "mupdf/tasks";
`loadPdf` -> `loadPDF`

2024-08-19 12:25 UTC, jamie-lemon commented on docs/how-to-guide/migration/index.rst
> +      const doc = loadPdf(arrayBuf); // Returns a Document instance
`loadPdf` -> `loadPDF`

2024-08-21 23:01 UTC, jamie-lemon approved these changes

2024-08-21 23:02 UTC, merged