working react example
ArtifexSoftware/mupdf.js pull request #52
Opened 2024-04-15 13:13 UTC by Vilhelm-Ian

2024-04-15 22:52 UTC, jamie-lemon requested changes
Added some layout tips which should help.

The main thing though is - can we somehow reference what would exist in `../../dist` for the libraries? We don't really want to duplicate this in `public`. If there is no way around it then update the README to inform the user about what they need to copy into "public".

2024-04-15 22:52 UTC, jamie-lemon commented on examples/mupdf-react/src/App.css
> +body {
Change this to `.App` to target the React DOM class for better layout

2024-04-15 22:52 UTC, jamie-lemon commented on examples/mupdf-react/src/App.css
> +  position: relative;
Change to:
```
postion: sticky
top:0
z-index:1
```
For better layout

2024-04-15 22:52 UTC, jamie-lemon commented on examples/mupdf-react/src/App.css
> +
Add a new DOM target with:
```
#outline-panel {
  position: fixed;
  top: 25px;
  height: 100vh;
  overflow-y: scroll;
}
```
For better layout :)

2024-04-15 22:52 UTC, jamie-lemon commented on examples/mupdf-react/src/viewer.js
> +	var page_size = await worker.getPageSize(current_doc, page_count > 1 ? 2 : 1)
Out of index by 1. Change to `1 ? 1 : 0` ( note this is also a bug in the current simple viewer, https://github.com/ArtifexSoftware/mupdf.js/commit/91228c47b452d27e9e106ff5353afb9e6fe26f63 )

2024-04-15 22:52 UTC, jamie-lemon commented on examples/mupdf-react/src/App.js
> +            <li onClick={()=>Viewer.toggle_fullscreen()}>Fullscreen</li>
Weird indentation from here ....

2024-04-23 21:37 UTC, Vilhelm-Ian commented
> Added some layout tips which should help.
> 
> The main thing though is - can we somehow reference what would exist in `../../dist` for the libraries? We don't really want to duplicate this in `public`. If there is no way around it then update the README to inform the user about what they need to copy into "public".

I couldn't find a way to get it to work without copying every file from dist

2024-05-09 18:36 UTC, closed without merging